const fallbackData = {
  site: { whatsapp:"966540394555", address_ar:"الطائف - شارع الستين", address_en:"Taif - 60th Street", map_url:"https://maps.app.goo.gl/5cZ4MrckUV79ZdHf9", map_embed:"https://www.google.com/maps?q=21.4427328,40.483089&z=17&output=embed" },
  values: [
    {icon:"✦", ar:"الجودة", en:"Quality", ar_desc:"تقديم الرعاية الصحية بمستوى مهني متميز.", en_desc:"Professional healthcare delivered to a high standard."},
    {icon:"♥", ar:"المريض أولاً", en:"Patient First", ar_desc:"احتياجات المريض محور الخدمة والرعاية.", en_desc:"Patient needs are at the center of our care."},
    {icon:"◎", ar:"العمل كفريق", en:"Teamwork", ar_desc:"تكامل الخبرات لتقديم تجربة صحية أفضل.", en_desc:"Integrated expertise for better care."},
    {icon:"◇", ar:"الاحترام", en:"Respect", ar_desc:"احترام جميع المرضى والزائرين والمحافظة على كرامتهم.", en_desc:"Respect for every patient and visitor."}
  ],
  departments: [
    {ar:"عيادة الباطنة",en:"Internal Medicine",desc_ar:"تشخيص وعلاج ومتابعة الأمراض الباطنية والمزمنة.",desc_en:"Diagnosis and follow-up of internal and chronic conditions."},
    {ar:"عيادة الأسنان",en:"Dental Clinic",desc_ar:"خدمات أسنان علاجية وتجميلية متكاملة.",desc_en:"Integrated restorative and cosmetic dental care."},
    {ar:"عيادة الطب العام",en:"General Medicine",desc_ar:"رعاية أولية وخدمات طبية عامة للمرضى.",desc_en:"Primary and general medical care."},
    {ar:"عيادة طب الأطفال",en:"Pediatrics",desc_ar:"رعاية الطفل ومتابعة صحته ونموه.",desc_en:"Child healthcare and growth follow-up."},
    {ar:"الطوارئ",en:"Emergency",desc_ar:"استقبال الحالات الطارئة وتقديم الرعاية الأولية.",desc_en:"Initial care for urgent and emergency cases."},
    {ar:"عيادة الجلدية",en:"Dermatology",desc_ar:"الجلدية والتجميل والليزر بأجهزة وتقنيات حديثة.",desc_en:"Dermatology, aesthetics and laser technologies."},
    {ar:"عيادة النساء والولادة",en:"Obstetrics & Gynecology",desc_ar:"متابعة صحة المرأة والحمل والولادة.",desc_en:"Women’s health, pregnancy and obstetric care."},
    {ar:"فحص العمالة",en:"Medical Screening",desc_ar:"الفحص الطبي للعمالة والفحوصات المطلوبة.",desc_en:"Medical screening and required examinations."},
    {ar:"قسم المختبر",en:"Laboratory",desc_ar:"تحاليل مخبرية باستخدام أجهزة حديثة.",desc_en:"Laboratory testing with modern equipment."},
    {ar:"قسم الأشعة",en:"Radiology",desc_ar:"خدمات الأشعة والتصوير الطبي.",desc_en:"Diagnostic imaging and radiology services."},
    {ar:"الصيدليات",en:"Pharmacies",desc_ar:"أدوية ومستلزمات طبية وخدمة على مدار الساعة حسب الفرع.",desc_en:"Medicines and medical supplies, with 24-hour service at selected branches."},
    {ar:"شركات التأمين",en:"Insurance",desc_ar:"خدمة حاملي بطاقات شركات التأمين المعتمدة.",desc_en:"Support for approved insurance card holders."}
  ],
  devices: [
    {name:"Spectra XT", ar:"تقنيات الليزر والعناية بالبشرة", en:"Laser and skin-care technology"},
    {name:"GentleMax Pro Plus", ar:"تقنيات متقدمة لإزالة الشعر والليزر", en:"Advanced hair removal and laser technology"},
    {name:"Action II", ar:"تقنيات تجميل وتجديد البشرة", en:"Aesthetic and skin rejuvenation technology"},
    {name:"Clarity II", ar:"ليزر ثنائي الموجة لتطبيقات الجلدية", en:"Dual-wavelength dermatology laser"}
  ],
  insurance: ["GlobeMed","Saudi Enaya","Aljazira Takaful","MedGulf","Malath","Walaa","NextCare","Tawuniya","TUC","AXA","TCS","Liva","Cigna","Bupa Arabia"],
  partners: [
    {ar:"شركة أبناء عبدالله باغفار المحدودة",en:"Abdullah A. Baghffar Sons Co., Ltd.",logo:"assets/partners/partner-01.jpg",active:true},
    {ar:"شركة مكتب الكمال للاستيراد المحدودة",en:"Alkamal Import Office Co.",logo:"assets/partners/partner-02.jpg",active:true},
    {ar:"شركة إمداد للأعمال الطبية",en:"Imdad Medical Business",logo:"assets/partners/partner-03.jpg",active:true},
    {ar:"الشركة الرابية الحديثة للتجارة",en:"Modern Rabiyah Trading Company",logo:"assets/partners/partner-04.jpg",active:true},
    {ar:"الشركة السعودية الخليجية سيبكو",en:"SEPCO Environment",logo:"assets/partners/partner-05.jpg",active:true},
    {ar:"شركة بسام بن محمد الشقراوي وشركاؤه للاستشارات المهنية",en:"BMB & Co Advisory & Assurance",logo:"assets/partners/partner-06.jpg",active:true},
    {ar:"شركة الخدمات الطبية والصيدلانية بشرى شكيب",en:"Medical & Pharmaceutical Services",logo:"assets/partners/partner-07.jpg",active:true},
    {ar:"شركة مختبر الجودة الطبي",en:"Aljawadah Medical Laboratory Company",logo:"assets/partners/partner-08.jpg",active:true},
    {ar:"شركة صفوة التشخيص الطبية",en:"Diagnostics Elite",logo:"assets/partners/partner-09.jpg",active:true},
    {ar:"مجمع جمجوم",en:"Jamjoom Medical Solutions",logo:"assets/partners/partner-10.jpg",active:true},
    {ar:"شركة العرفج للتجارة والاستيراد",en:"Alarfaj Commercial & Imports Co.",logo:"assets/partners/partner-11.jpg",active:true},
    {ar:"شركة المرمر الأبيض للخدمات الطبية",en:"Al Marmar Dental Co.",logo:"assets/partners/partner-12.jpg",active:true}
  ]
};

const I18N={
 ar:{"nav.home":"الرئيسية","nav.about":"عن المجمع","nav.departments":"الأقسام","nav.devices":"الأجهزة","nav.insurance":"التأمين","nav.partners":"سابقة الأعمال","nav.requests":"الطلبات","nav.contact":"تواصل معنا","brand.slogan":"صحتك أولويتنا","actions.book":"احجز موعد","actions.bookNow":"احجز موعدك","actions.whatsapp":"تواصل واتساب","actions.bookDepartment":"احجز حسب التخصص ←","hero.eyebrow":"مجمع أطباء الستين الطبي العام","hero.title":"صحتك أولويتنا","hero.text":"رعاية طبية متكاملة تجمع الخبرة، التقنيات الحديثة، والاهتمام الحقيقي بك وبعائلتك.","hero.q1":"تخصصات متعددة","hero.q2":"أحدث الأجهزة","hero.q3":"شركات تأمين معتمدة","hero.card":"رعاية تليق بك","about.kicker":"من نحن","about.title":"رعاية صحية بمعايير واضحة","about.text":"نعمل على تقديم خدمات علاجية وتجميلية متكاملة، ونضع المريض واحتياجاته في قلب تجربة الرعاية.","departments.kicker":"التخصصات والخدمات","departments.title":"كل ما تحتاجه في مكان واحد","devices.kicker":"التقنيات الطبية","devices.title":"أجهزة وتقنيات حديثة","insurance.kicker":"شركاء التأمين","insurance.title":"نرحب بحاملي بطاقات شركات التأمين المعتمدة","corporate.kicker":"خدمات الشركات","corporate.title":"حلول طبية للشركات والموظفين","corporate.text":"فحص العمالة، الفحوصات الدورية، والتعاقدات المباشرة للشركات.","corporate.cta":"طلب تعاقد","partners.kicker":"سابقة الأعمال والموردون","partners.title":"شركاء وموردون نفخر بالتعامل معهم","partners.text":"مجموعة من الجهات والموردين الذين يظهرون ضمن الملف التعريفي للمجمع.","requests.kicker":"الطلبات","requests.title":"كيف يمكننا مساعدتك؟","requests.text":"حجز موعد، طلب تعاقد، أو إرسال شكوى واقتراح من نفس المكان.","requests.booking":"حجز موعد","requests.contract":"طلب تعاقد","requests.complaint":"شكوى أو اقتراح","contract.company":"اسم الشركة","contract.contact":"اسم مسؤول التواصل","contract.email":"البريد الإلكتروني","contract.details":"تفاصيل الطلب","contract.send":"إرسال طلب التعاقد عبر واتساب","feedback.type":"نوع الطلب","feedback.details":"التفاصيل","feedback.send":"إرسال عبر واتساب","booking.kicker":"الحجز","booking.title":"احجز موعدك عبر واتساب","booking.text":"املأ البيانات وسيتم تجهيز رسالة الحجز تلقائيًا لإرسالها إلى المجمع.","form.name":"الاسم","form.mobile":"رقم الجوال","form.department":"التخصص","form.date":"التاريخ","form.time":"الوقت","form.notes":"ملاحظات","form.send":"إرسال الحجز عبر واتساب","contact.kicker":"تواصل معنا","contact.title":"نحن قريبون منك","contact.address":"الطائف - شارع الستين","contact.map":"فتح Google Maps","footer.rights":"مجمع أطباء الستين الطبي العام. جميع الحقوق محفوظة.","footer.admin":"إدارة الموقع"},
 en:{"nav.home":"Home","nav.about":"About","nav.departments":"Departments","nav.devices":"Devices","nav.insurance":"Insurance","nav.partners":"Partners","nav.requests":"Requests","nav.contact":"Contact","brand.slogan":"Your Health, Our Priority","actions.book":"Book","actions.bookNow":"Book Appointment","actions.whatsapp":"WhatsApp","actions.bookDepartment":"Book by department →","hero.eyebrow":"Alsiteen Doctors General Medical Company","hero.title":"Your Health, Our Priority","hero.text":"Integrated medical care combining expertise, modern technology and genuine attention to you and your family.","hero.q1":"Multiple specialties","hero.q2":"Modern technology","hero.q3":"Approved insurance","hero.card":"Care that fits you","about.kicker":"About us","about.title":"Healthcare with clear standards","about.text":"We provide integrated therapeutic and aesthetic services with patients at the heart of every care experience.","departments.kicker":"Departments & services","departments.title":"Everything you need in one place","devices.kicker":"Medical technology","devices.title":"Modern devices and technologies","insurance.kicker":"Insurance partners","insurance.title":"We welcome approved insurance card holders","corporate.kicker":"Corporate services","corporate.title":"Medical solutions for companies","corporate.text":"Employee screening, periodic examinations and direct corporate contracts.","corporate.cta":"Request Contract","partners.kicker":"Track record & suppliers","partners.title":"Partners and suppliers we value","partners.text":"A selection of organizations and suppliers listed in the medical complex profile.","requests.kicker":"Requests","requests.title":"How can we help?","requests.text":"Book an appointment, request a corporate contract, or send a complaint/suggestion.","requests.booking":"Book Appointment","requests.contract":"Contract Request","requests.complaint":"Complaint or Suggestion","contract.company":"Company Name","contract.contact":"Contact Person","contract.email":"Email","contract.details":"Request Details","contract.send":"Send contract request via WhatsApp","feedback.type":"Request Type","feedback.details":"Details","feedback.send":"Send via WhatsApp","booking.kicker":"Booking","booking.title":"Book your appointment via WhatsApp","booking.text":"Complete the form and we will prepare your booking message automatically.","form.name":"Name","form.mobile":"Mobile","form.department":"Department","form.date":"Date","form.time":"Time","form.notes":"Notes","form.send":"Send booking via WhatsApp","contact.kicker":"Contact","contact.title":"We are close to you","contact.address":"Taif - 60th Street","contact.map":"Open Google Maps","footer.rights":"Alsiteen Doctors General Medical Company. All rights reserved.","footer.admin":"Site Admin"}
};

let lang=localStorage.getItem('siteLang')||'ar';
let data=fallbackData;
function t(k){return I18N[lang][k]||k}
function applyLang(){document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';document.getElementById('langBtn').textContent=lang==='ar'?'EN':'AR';document.querySelectorAll('[data-i18n]').forEach(el=>el.textContent=t(el.dataset.i18n));renderAll()}
function renderAll(){
 document.getElementById('valuesGrid').innerHTML=data.values.map(v=>`<article class="value-card"><div class="icon-badge">${v.icon||'✦'}</div><h3>${lang==='ar'?v.ar:v.en}</h3><p>${lang==='ar'?v.ar_desc:v.en_desc}</p></article>`).join('');
 const departments=data.departments.filter(x=>String(x.active??'true')!=='false');
 const deptIcons=['✚','◉','⌁','♡','✦','◇','♀','✓','⚗','◫','Rx','⊕'];
 document.getElementById('departmentsGrid').innerHTML=departments.map((d,i)=>`<article class="dept-card"><div class="dept-icon">${deptIcons[i%deptIcons.length]}</div><h3>${lang==='ar'?d.ar:d.en}</h3><p>${lang==='ar'?d.desc_ar:d.desc_en}</p><span class="dept-arrow">↗</span></article>`).join('');
 document.getElementById('devicesGrid').innerHTML=data.devices.filter(x=>String(x.active??'true')!=='false').map((d,i)=>`<article class="device-card"><div class="device-no">TECH ${String(i+1).padStart(2,'0')}</div><h3>${d.name}</h3><p>${lang==='ar'?d.ar:d.en}</p></article>`).join('');
 const ins=(data.insurance||[]).filter(Boolean); const doubled=[...ins,...ins]; document.getElementById('insuranceTrack').innerHTML=doubled.map(x=>`<div class="insurance-pill">${typeof x==='string'?x:(x.name||'')}</div>`).join('');
 const partners=(data.partners||fallbackData.partners||[]).filter(x=>String(x.active??'true')!=='false');
 const pg=document.getElementById('partnersGrid'); if(pg) pg.innerHTML=partners.map(p=>`<article class="partner-card"><img src="${p.logo||''}" alt="${lang==='ar'?(p.ar||''):(p.en||p.ar||'')}" loading="lazy"><h3>${lang==='ar'?(p.ar||''):(p.en||p.ar||'')}</h3></article>`).join('');
 const sel=document.getElementById('department'); sel.innerHTML=`<option value="">${lang==='ar'?'اختر التخصص':'Choose department'}</option>`+departments.map(d=>`<option>${lang==='ar'?d.ar:d.en}</option>`).join('');
}
function jsonp(url){return new Promise((resolve,reject)=>{const cb='cb_'+Date.now();const s=document.createElement('script');window[cb]=(r)=>{delete window[cb];s.remove();resolve(r)};s.onerror=()=>{delete window[cb];s.remove();reject(new Error('load failed'))};s.src=url+(url.includes('?')?'&':'?')+'action=publicData&callback='+cb+'&_='+Date.now();document.body.appendChild(s)})}
async function loadRemote(){const url=window.SITE_CONFIG?.appsScriptUrl;if(!url)return;document.body.classList.add('loading');try{const res=await jsonp(url);if(res?.ok&&res.data){data={...fallbackData,...res.data,partners:(res.data.partners&&res.data.partners.length?res.data.partners:fallbackData.partners)};renderAll()}else if(res && res.error){throw new Error(res.error)}}catch(e){console.error('Apps Script:',e);showError(lang==='ar'?'تعذر الاتصال بقاعدة البيانات. راجع نشر Apps Script.':'Could not connect to the database. Check Apps Script deployment.')}finally{document.body.classList.remove('loading')}}
function showError(msg){const x=document.createElement('div');x.className='error-banner';x.textContent=msg;document.body.appendChild(x);setTimeout(()=>x.remove(),4500)}
function waLink(text=''){const number=data.site?.whatsapp||window.SITE_CONFIG?.whatsapp||'966540394555';return `https://wa.me/${number}?text=${encodeURIComponent(text)}`}
function setStaticLinks(){document.getElementById('waHero').href=waLink(lang==='ar'?'مرحباً، تواصلت معكم من الموقع وأرغب في الاستفسار.':'Hello, I contacted you from the website and would like to ask a question.');const corp=document.getElementById('waCorporate');if(corp) corp.href='#requests';document.getElementById('waContact').href=waLink();document.getElementById('waFloat').href=waLink();document.getElementById('linktreeLink').href=window.SITE_CONFIG?.linktree||'#';document.getElementById('snapLink').href=window.SITE_CONFIG?.snapchat||'#';const ml=document.getElementById('mapLink');if(ml)ml.href=data.site?.map_url||'https://maps.app.goo.gl/5cZ4MrckUV79ZdHf9';const mf=document.getElementById('mapFrame');if(mf)mf.src=data.site?.map_embed||'https://www.google.com/maps?q=21.4427328,40.483089&z=17&output=embed';const at=document.getElementById('addressText');if(at)at.textContent=lang==='ar'?(data.site?.address_ar||'الطائف - شارع الستين'):(data.site?.address_en||'Taif - 60th Street')}
const oldRender=renderAll;renderAll=function(){oldRender();setStaticLinks()}
document.getElementById('langBtn').addEventListener('click',()=>{lang=lang==='ar'?'en':'ar';localStorage.setItem('siteLang',lang);applyLang()});
document.getElementById('menuToggle').addEventListener('click',()=>document.getElementById('mainNav').classList.toggle('open'));
document.querySelectorAll('#mainNav a').forEach(a=>a.addEventListener('click',()=>document.getElementById('mainNav').classList.remove('open')));
document.getElementById('bookingForm').addEventListener('submit',e=>{e.preventDefault();const v=id=>document.getElementById(id).value.trim();const msg=lang==='ar'?`طلب حجز من الموقع\nالاسم: ${v('name')}\nالجوال: ${v('mobile')}\nالتخصص: ${v('department')}\nالتاريخ: ${v('date')}\nالوقت: ${v('time')}\nملاحظات: ${v('notes')||'-'}`:`Website booking request\nName: ${v('name')}\nMobile: ${v('mobile')}\nDepartment: ${v('department')}\nDate: ${v('date')}\nTime: ${v('time')}\nNotes: ${v('notes')||'-'}`;window.open(waLink(msg),'_blank')});
function openRequest(type='booking'){
 document.querySelectorAll('.request-tab').forEach(b=>b.classList.toggle('active',b.dataset.requestTab===type));
 document.querySelectorAll('.request-form').forEach(f=>f.classList.toggle('active',f.dataset.form===type));
 document.getElementById('requests')?.scrollIntoView({behavior:'smooth',block:'start'});
}
document.querySelectorAll('[data-request]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();openRequest(a.dataset.request||'booking');document.querySelector('.requests-menu')?.classList.remove('open')}));
document.querySelectorAll('.request-tab').forEach(b=>b.addEventListener('click',()=>openRequest(b.dataset.requestTab)));
document.querySelector('.requests-toggle')?.addEventListener('click',e=>{e.stopPropagation();document.querySelector('.requests-menu')?.classList.toggle('open')});
document.addEventListener('click',()=>document.querySelector('.requests-menu')?.classList.remove('open'));
document.getElementById('contractForm')?.addEventListener('submit',e=>{e.preventDefault();const v=id=>document.getElementById(id).value.trim();const msg=lang==='ar'?`طلب تعاقد من الموقع\nاسم الشركة: ${v('companyName')}\nمسؤول التواصل: ${v('companyContact')}\nالجوال: ${v('companyMobile')}\nالبريد الإلكتروني: ${v('companyEmail')||'-'}\nتفاصيل الطلب: ${v('companyDetails')||'-'}`:`Website contract request\nCompany: ${v('companyName')}\nContact: ${v('companyContact')}\nMobile: ${v('companyMobile')}\nEmail: ${v('companyEmail')||'-'}\nDetails: ${v('companyDetails')||'-'}`;window.open(waLink(msg),'_blank')});
document.getElementById('complaintForm')?.addEventListener('submit',e=>{e.preventDefault();const v=id=>document.getElementById(id).value.trim();const msg=lang==='ar'?`${v('feedbackType')} من الموقع\nالاسم: ${v('feedbackName')}\nالجوال: ${v('feedbackMobile')}\nالتفاصيل: ${v('feedbackDetails')}`:`Website feedback\nName: ${v('feedbackName')}\nMobile: ${v('feedbackMobile')}\nType: ${v('feedbackType')}\nDetails: ${v('feedbackDetails')}`;window.open(waLink(msg),'_blank')});
const today=new Date();document.getElementById('date').min=[today.getFullYear(),String(today.getMonth()+1).padStart(2,'0'),String(today.getDate()).padStart(2,'0')].join('-');document.getElementById('year').textContent=new Date().getFullYear();applyLang();loadRemote();
