module.exports={
 settings:{
 siteNameAr:"مجمع أطباء الستين الطبي العام",siteNameEn:"Alsiteen Doctors General Medical Complex",sloganAr:"صحتك أولويتنا",sloganEn:"Your Health Is Our Priority",
 seoTitleAr:"مجمع أطباء الستين الطبي العام",seoTitleEn:"Alsiteen Doctors General Medical Complex",seoDescriptionAr:"مجمع أطباء الستين الطبي العام بالطائف - صحتك أولويتنا.",seoDescriptionEn:"Alsiteen Doctors General Medical Complex in Taif - Your Health Is Our Priority.",
 heroEyebrowAr:"مجمع أطباء الستين الطبي العام",heroEyebrowEn:"Alsiteen Doctors General Medical Complex",heroTitleAr:"صحتك أولويتنا",heroTitleEn:"Your Health Is Our Priority",heroTextAr:"رعاية طبية شاملة تجمع الخبرة الطبية والتقنيات الحديثة وسرعة الخدمة تحت سقف واحد.",heroTextEn:"Comprehensive medical care combining clinical expertise, modern technology and efficient service under one roof.",heroImage:"assets/reception-clean.webp",
 aboutTitleAr:"رعاية متكاملة بمعايير مهنية",aboutTitleEn:"Integrated Care with Professional Standards",aboutTextAr:"يهدف مجمع أطباء الستين إلى تقديم خدمات صحية متكاملة مع التركيز على الجودة وراحة المراجع وسرعة إنجاز الإجراءات.",aboutTextEn:"Alsiteen Doctors General Medical Complex provides integrated healthcare with a focus on quality, patient comfort and efficient service.",missionAr:"نهتم بالجانب الإيجابي لصحة المجتمع من خلال المعيشة الآمنة والاستخدام الداخلي والخارجي، والتأكيد على الوقاية من العلاج.",missionEn:"We support community health through safe living, responsible practices and a strong emphasis on prevention.",visionAr:"خلق حلول الرعاية الصحية الشاملة والمتميزة بمعايير احترافية ونهج حديث.",visionEn:"To provide comprehensive healthcare solutions with professional standards and a modern approach.",valuesAr:"العدالة، النزاهة، المريض هو اهتمامنا الأول، العمل كفريق واحد، الاحترام، والحفاظ على كرامة المريض.",valuesEn:"Fairness, integrity, patient-first care, teamwork, respect and preserving patient dignity.",aboutImage:"assets/corridor-clean.webp",
 servicesLabelAr:"التخصصات والخدمات",servicesLabelEn:"Specialties & Services",servicesTitleAr:"اختر الخدمة التي تناسب احتياجك",servicesTitleEn:"Choose the service that fits your needs",servicesIntroAr:"قسمنا الخدمات إلى مجموعات واضحة لتصل إلى العيادة أو القسم المطلوب بسرعة، ويمكنك حجز الموعد مباشرة من بطاقة الخدمة.",servicesIntroEn:"Services are grouped clearly so you can reach the right clinic or department quickly and book directly.",
 journeyLabelAr:"رحلة صحية متكاملة",journeyLabelEn:"Integrated Care Journey",journeyTitleAr:"من الاستشارة إلى التشخيص والعلاج",journeyTitleEn:"From Consultation to Diagnosis and Treatment",journeyTextAr:"يضم المجمع عيادات خارجية، مختبر، أشعة، صيدلية، فحص عمالة وخدمات تأمين وشركات لتسهيل رحلة المراجع.",journeyTextEn:"The complex includes outpatient clinics, laboratory, radiology, pharmacy, employment checks, insurance and corporate services.",journeyImage:"assets/dental-clean.webp",
 insuranceLabelAr:"شركاء التأمين",insuranceLabelEn:"Insurance Partners",insuranceTitleAr:"نتعامل مع مجموعة واسعة من شركات التأمين",insuranceTitleEn:"We work with a wide network of insurers",insuranceNoteAr:"تعتمد التغطية على فئة الوثيقة وموافقة شركة التأمين.",insuranceNoteEn:"Coverage depends on policy class and insurer approval.",suppliersLabelAr:"سابقة الأعمال والموردين",suppliersLabelEn:"Partners & Suppliers",suppliersTitleAr:"شركاء وموردون نفخر بالتعامل معهم",suppliersTitleEn:"Partners and suppliers we are proud to work with",
 contactLabelAr:"تواصل معنا",contactLabelEn:"Contact Us",contactTitleAr:"نحن أقرب مما تتخيل",contactTitleEn:"We are closer than you think",doctorsLabelAr:"أطباؤنا",doctorsLabelEn:"Our Doctors",doctorsTitleAr:"تعرف على فريقنا الطبي",doctorsTitleEn:"Meet Our Medical Team",doctorsIntroAr:"نخبة من الأطباء ذوي الخبرة في تخصصات متعددة لخدمتكم بأعلى معايير الرعاية.",doctorsIntroEn:"Meet our experienced physicians across multiple specialties, committed to high standards of care.",footerContactKickerAr:"تواصل معنا",footerContactKickerEn:"Contact Us",footerContactTitleAr:"نحن أقرب مما تتخيل",footerContactTitleEn:"We are closer than you think",footerContactTextAr:"للاستفسارات الطبية أو التأمين أو خدمات الشركات، تواصل معنا وسنوجهك إلى القسم المناسب.",footerContactTextEn:"For medical inquiries, insurance, or corporate services, contact us and we will direct you to the right department.",footerAboutAr:"رعاية طبية متكاملة في الطائف، تجمع العيادات والخدمات التشخيصية والتأمينية في مكان واحد.",footerAboutEn:"Integrated healthcare in Taif, bringing clinics, diagnostics, insurance and support services together in one place.",copyrightAr:"© 2026 مجمع أطباء الستين الطبي العام. جميع الحقوق محفوظة.",copyrightEn:"© 2026 Alsiteen Doctors General Medical Complex. All rights reserved.",
 addressAr:"الطائف - الحوية، شارع الستين.",addressEn:"Taif - Al Hawiyah, Al Siteen Street.",phone:"0127251700",whatsapp:"966540394555",email:"Admin@alsiteendoctor.com",mapLink:"https://maps.app.goo.gl/Nybbty1Em6jc9p2F9",mapEmbed:"https://www.google.com/maps?q=%D9%85%D8%AC%D9%85%D8%B9%20%D8%A3%D8%B7%D8%A8%D8%A7%D8%A1%20%D8%A7%D9%84%D8%B3%D8%AA%D9%8A%D9%86%20%D8%A7%D9%84%D8%B7%D8%A8%D9%8A%20%D8%A7%D9%84%D8%B9%D8%A7%D9%85%20%D8%A7%D9%84%D8%B7%D8%A7%D8%A6%D9%81&output=embed",shopUrl:"https://salla.sa/alsiteen60",whatsappMessage:"أتواصل معكم من خلال الموقع للاستفسار",offersSource:"excel-import",themeNavy:"#12365f",themeNavyDark:"#0d2949",themeRed:"#ed1c24",themeLight:"#f6f8fb"
 },
 stats:[{icon:"◎",value:1,suffix:"",labelAr:"هدفنا رعايتكم",labelEn:"Your care is our goal",active:true},{icon:"✚",value:11,suffix:"+",labelAr:"أكثر من 11 تخصص",labelEn:"More than 11 specialties",active:true},{icon:"✓",value:5000,suffix:"+",labelAr:"خدمتنا أكثر من 5000 خدمة",labelEn:"More than 5,000 services delivered",active:true},{icon:"◇",value:13,suffix:"+",labelAr:"أكثر من 13 شريك تأمين",labelEn:"More than 13 insurance partners",active:true},{icon:"▦",value:1000,suffix:"+",labelAr:"خدمنا أكثر من 1,000 شركة",labelEn:"More than 1,000 companies served",active:true},{icon:"♟",value:100000,suffix:"+",labelAr:"خدمنا أكثر من 100,000 عميل",labelEn:"More than 100,000 clients served",active:true}],
 socials:[{icon:"◎",name:"Instagram",handle:"@alsiteen60",url:"https://www.instagram.com/alsiteen60/",active:true},{icon:"♪",name:"TikTok",handle:"@alsiteen60",url:"https://www.tiktok.com/@alsiteen60",active:true},{icon:"◉",name:"Snapchat",handle:"@alsieen60",url:"https://www.snapchat.com/@alsieen60",active:true},{icon:"↗",name:"Linktree",handle:"كل الروابط",url:"https://linktr.ee/alsiteen60",active:true}],
 services:[{cat:"clinics",icon:"🩺",ar:"عيادة الطب العام",en:"General Medicine",descAr:"الرعاية الأولية والتقييم العام للحالات الصحية.",descEn:"Primary care and general health assessment.",active:true},{cat:"clinics",icon:"🫀",ar:"عيادة الباطنة",en:"Internal Medicine",descAr:"تشخيص ومتابعة الأمراض الباطنية والمزمنة.",descEn:"Diagnosis and follow-up of internal and chronic conditions.",active:true},{cat:"clinics",icon:"👩‍⚕️",ar:"عيادة النساء والولادة",en:"Obstetrics & Gynecology",descAr:"متابعة صحة المرأة والحمل وخدمات النساء والولادة.",descEn:"Women's health, pregnancy and obstetric care.",active:true},{cat:"clinics",icon:"🧒",ar:"عيادة الأطفال",en:"Pediatrics",descAr:"متابعة صحة الأطفال والنمو والحالات الشائعة.",descEn:"Child health, development and common pediatric conditions.",active:true},{cat:"clinics",icon:"🦷",ar:"عيادة الأسنان",en:"Dental Clinic",descAr:"خدمات علاجية وتجميلية متكاملة لصحة الفم والأسنان.",descEn:"Comprehensive therapeutic and cosmetic dental services.",active:true},{cat:"clinics",icon:"✨",ar:"عيادة الجلدية والليزر",en:"Dermatology & Laser",descAr:"العناية بالبشرة والجلدية والليزر والإجراءات التجميلية.",descEn:"Dermatology, skin care, laser and aesthetic procedures.",active:true},{cat:"diagnostics",icon:"🧪",ar:"قسم المختبر",en:"Laboratory",descAr:"تحاليل وفحوصات مخبرية لدعم التشخيص والمتابعة.",descEn:"Laboratory tests supporting diagnosis and follow-up.",active:true},{cat:"diagnostics",icon:"🩻",ar:"قسم الأشعة",en:"Radiology",descAr:"خدمات تصوير وتشخيص مساندة للرعاية الطبية.",descEn:"Diagnostic imaging services supporting clinical care.",active:true},{cat:"support",icon:"🧾",ar:"فحص العمالة",en:"Employment Medical Check",descAr:"فحوصات العمالة والإقامة والرخص وفق المتطلبات.",descEn:"Employment, residency and licensing medical checks.",active:true},{cat:"support",icon:"🚑",ar:"الطوارئ",en:"Emergency",descAr:"استقبال وتقييم الحالات التي تحتاج إلى رعاية عاجلة.",descEn:"Assessment and care for urgent medical conditions.",active:true},{cat:"support",icon:"💊",ar:"الصيدليات",en:"Pharmacies",descAr:"أدوية ومستلزمات طبية وخدمة الوصفات.",descEn:"Medicines, medical supplies and prescription services.",active:true}],
 offers:[],insurers:[
{ar:"الاتحاد للتأمين",en:"Aletihad Insurance",image:"assets/insurance-uploaded/aletihad.jpg",active:true},
{ar:"تكافل الراجحي",en:"Al Rajhi Takaful",image:"assets/insurance-uploaded/alrajhi.png",active:true},
{ar:"بوبا العربية",en:"Bupa Arabia",image:"assets/insurance-uploaded/bupa.png",active:true},
{ar:"مجموعة الخليج للتأمين",en:"Gulf Insurance Group",image:"assets/insurance-uploaded/gig.png",active:true},
{ar:"غلوب مد",en:"GlobeMed",image:"assets/insurance-uploaded/globemed.png",active:true},
{ar:"اتحاد الخليج الأهلية",en:"Gulf Union Cooperative Insurance",image:"assets/insurance-uploaded/gulf-union.png",active:true},
{ar:"ملاذ للتأمين",en:"Malath Insurance",image:"assets/insurance-uploaded/malath.png",active:true},
{ar:"ميدنت",en:"MedNet",image:"assets/insurance-uploaded/mednet.jpg",active:true},
{ar:"نكست كير",en:"NextCare",image:"assets/insurance-uploaded/nextcare.png",active:true},
{ar:"تكافل العربية",en:"Takaful Al Arabia",image:"assets/insurance-uploaded/takaful-arabia.jpg",active:true},
{ar:"التعاونية",en:"Tawuniya",image:"assets/insurance-uploaded/tawuniya.png",active:true},
{ar:"العناية الشاملة السعودية TCS",en:"TCS",image:"assets/insurance-uploaded/tcs.jpg",active:true},
{ar:"ولاء",en:"Walaa",image:"assets/insurance-uploaded/walaa.png",active:true},
{ar:"مجمع نهج الشفاء الطبي العام",en:"Nahj Al-Shifaa General Medical Complex",image:"assets/insurance-uploaded/nahj-alshifaa.png",active:true}
],suppliers:[
{ar:"شركة أبناء عبدالله بالغفار المحدودة",en:"Abdullah A. Baghaffar Sons Co., Ltd.",image:"assets/supplier-01.jpg",active:true},
{ar:"شركة مكتب الكمال للاستيراد المحدودة",en:"Alkamal Import Office Co.",image:"assets/supplier-02.jpg",active:true},
{ar:"شركة إمداد للأعمال الطبية",en:"Imdad Medical Business",image:"assets/supplier-03.jpg",active:true},
{ar:"الشركة الرابعة الحديثة للتجارة",en:"Modern Rabiyah Trading Company",image:"assets/supplier-04.jpg",active:true},
{ar:"الشركة السعودية الخليجية سيبكو",en:"SEPCO Environment",image:"assets/supplier-05.jpg",active:true},
{ar:"شركة بسام بن محمد الثقافي وشركاؤه للاستشارات المهنية",en:"BMB&CO Advisory & Assurance",image:"assets/supplier-06.jpg",active:true},
{ar:"شركة الخدمات الطبية والصيدلانية بشير شكيب",en:"Medical & Pharmaceutical Services",image:"assets/supplier-07.jpg",active:true},
{ar:"شركة مختبر الجودة الطبي",en:"Aljawadah Medical Laboratory Company",image:"assets/supplier-08.jpg",active:true},
{ar:"شركة صفوة التشخيص الطبية",en:"Diagnostics Elite",image:"assets/supplier-09.jpg",active:true},
{ar:"مجمع جمجوم",en:"Jamjoom Medical Solutions",image:"assets/supplier-10.jpg",active:true},
{ar:"شركة العرفج للتجارة والاستيراد",en:"Al Arafaj Commercial & Imports Co.",image:"assets/supplier-11.jpg",active:true},
{ar:"شركة المرمر الأبيض للخدمات الطبية",en:"Al Marmar Dental Co.",image:"assets/supplier-12.jpg",active:true}
],
doctors:[]
}